Feat#issue 15
astrocamp/15th-RestTime pull request #16
Opened 2023-12-18 11:50 UTC by Adoraxuu

- 新增套件 gem 'rails-i18n'
- 修改 devise.tw.yml，將系統訊息改為中文
- 新增 zh-TW.yml客製化名稱

2023-12-18 12:11 UTC, kaochenlong requested changes

2023-12-18 12:11 UTC, kaochenlong commented on Gemfile
> +gem 'rails-i18n'
上課的時候就提過了，不用裝這東西

2023-12-18 13:25 UTC, Adoraxuu commented
- 修改 devise.tw.yml，將系統訊息改為中文
- 新增 zh-TW.yml客製化名稱
- 已移除套件 'rails-i18n'

2023-12-18 13:26 UTC, Adoraxuu commented
已移除套件 'rails-i18n'

2023-12-19 03:44 UTC, kaochenlong commented on config/application.rb
> +    config.i18n.default_locale = "zh-TW"
如果這裡用 `zh-TW` 的話，建議所有的檔案都統一寫成 `xxx.zh-TW.yml`，比較統一

或是，直接都改成 `tw` 也行

2023-12-19 03:48 UTC, ennis-hong approved these changes

2023-12-19 07:58 UTC, kaochenlong commented on app/views/shared/_form.html.erb
這個放在 `shared` 的話，其它的 `_form` 要放哪裡？還是全站只會有一個表單呢？

2023-12-19 08:02 UTC, Adoraxuu commented
- 修改application為config.i18n.default_locale = "tw"
- 統一將“zh-TW”改為"tw"(包含config.i18n.default_locale = "tw"、tw.yml內的文字、devise.tw.yml內的文字)
- 修改views>shared>_form.html.erb內的文字為i18n格式
- 在tw.yml內新增activerecord:attributes:product: ，讓錯誤訊息可以顯示中文
修改後：
<img width="624" alt="截圖 2023-12-19 下午3 57 01" src="https://github.com/astrocamp/15th-RestTime/assets/147526390/79547253-c96c-4912-8ef1-7a4ef060dcad">

修改前：
<img width="1429" alt="截圖 2023-12-19 下午3 40 31" src="https://github.com/astrocamp/15th-RestTime/assets/147526390/ceda165d-d4cf-47a7-a343-ea0120ec3ec6">

2023-12-19 08:04 UTC, Adoraxuu commented on app/views/shared/_form.html.erb
疏忽了，我再改放到Products內

2023-12-19 08:09 UTC, Adoraxuu commented
- 修改application為config.i18n.default_locale = "tw"
- 統一將“zh-TW”改為"tw"(包含config.i18n.default_locale = "tw"、tw.yml內的文字、devise.tw.yml內的文字)
- 修改views>shared>_form.html.erb內的文字為i18n格式
- 在tw.yml內新增activerecord:attributes:product: ，讓錯誤訊息可以顯示中文
修改後：
<img width="624" alt="截圖 2023-12-19 下午3 57 01" src="https://github.com/astrocamp/15th-RestTime/assets/147526390/06e2e484-aabd-4876-b7ff-f29c12526332">
修改前：
<img width="1039" alt="截圖 2023-12-19 下午3 52 15" src="https://github.com/astrocamp/15th-RestTime/assets/147526390/60d826bc-8958-4291-a4bc-055760ffa567">

- 將shared/_form.html.erb改放到products資料夾內

2023-12-19 08:14 UTC, Adoraxuu commented
- 修改application為config.i18n.default_locale = "tw"
- 統一將“zh-TW”改為"tw"(包含config.i18n.default_locale = "tw"、tw.yml內的文字、devise.tw.yml內的文字)
- 修改views>shared>_form.html.erb內的文字為i18n格式
- 在tw.yml內新增activerecord:attributes:product: ，讓錯誤訊息可以顯示中文
- 將shared/_form.html.erb改放到products資料夾內
- 修改後：
<img width="624" alt="截圖 2023-12-19 下午3 57 01" src="https://github.com/astrocamp/15th-RestTime/assets/147526390/06e2e484-aabd-4876-b7ff-f29c12526332">

- 修改前：
<img width="1429" alt="截圖 2023-12-19 下午3 40 31" src="https://github.com/astrocamp/15th-RestTime/assets/147526390/be7d62ac-c9e2-4b1f-b92e-9882b9bea1f2">

2023-12-19 09:02 UTC, Qkauia approved these changes

2023-12-19 09:09 UTC, sammong approved these changes

2023-12-19 09:59 UTC, Dorenchen approved these changes

2023-12-20 02:54 UTC, cacachang commented
有衝突

2023-12-20 02:58 UTC, cacachang approved these changes

2023-12-20 04:33 UTC, merged