Feat/issue 10 2
astrocamp/15th-RestTime pull request #21
Opened 2023-12-19 10:40 UTC by Dorenchen

開PR    本地已經解過了
靜態頁面  
-about.html.erb
-choose_us.html.erb
-join_us.html.erb
-contact_us.html.erb
-terms.html.erb
-privacy.html.erb
-refund_policy.html.erb
以上這些

2023-12-19 16:05 UTC, Qkauia approved these changes

2023-12-20 02:59 UTC, cacachang commented
需要解衝突

2023-12-20 03:26 UTC, cacachang requested changes

2023-12-20 03:26 UTC, cacachang commented on app/helpers/pages_helper.rb
> +module PagesHelper
沒有用到就可以刪掉

2023-12-20 03:26 UTC, cacachang commented on test/controllers/pages_controller_test.rb
> +require 'test_helper'
不需要用到可以刪除

2023-12-20 03:26 UTC, cacachang commented on app/views/pages/choose_us.html.erb
> +      <!-- <li class="inline"><a href="">常見問題</a></li> -->
為什麼這個要註解

2023-12-20 03:26 UTC, cacachang commented on app/views/products/index.html.erb
> +<%end%>
`<% end %>`

2023-12-20 03:26 UTC, cacachang commented on app/models/product.rb
>    validates :price, numericality: { greater_than: 0 }
這個 PR 看起來是不會動到 product 的驗證，看一下衝突有沒有誤刪

2023-12-20 06:46 UTC, Dorenchen commented on app/views/pages/choose_us.html.erb
> +      <!-- <li class="inline"><a href="">常見問題</a></li> -->
因為那時候是想在畫面上，先不要讓它呈現。
所以先註解掉。
但用不到了,我把它刪除掉

2023-12-20 07:42 UTC, Dorenchen commented on app/helpers/pages_helper.rb
> +module PagesHelper
已刪除~也修正了

2023-12-20 07:43 UTC, Dorenchen commented on test/controllers/pages_controller_test.rb
> +require 'test_helper'
以刪除~
也修正了

2023-12-20 07:43 UTC, Dorenchen commented on app/views/pages/choose_us.html.erb
> +      <!-- <li class="inline"><a href="">常見問題</a></li> -->
已刪除~
也修正了

2023-12-20 07:43 UTC, Dorenchen commented on app/views/products/index.html.erb
> +<%end%>
修改好了

2023-12-20 07:44 UTC, Dorenchen commented on app/models/product.rb
>    validates :price, numericality: { greater_than: 0 }
補上去了~
恢復驗證

2023-12-20 07:47 UTC, sammong approved these changes

2023-12-20 08:00 UTC, Qkauia approved these changes

2023-12-20 08:42 UTC, ennis-hong approved these changes

2023-12-21 02:51 UTC, merged