Feat issue 04
astrocamp/15th-RestTime pull request #37
Opened 2023-12-19 16:28 UTC by Qkauia

- add shop table
- rubocop done

2023-12-19 16:40 UTC, Dorenchen approved these changes

2023-12-20 04:10 UTC, cacachang requested changes

2023-12-20 04:10 UTC, cacachang commented on db/migrate/20231219141519_create_shops.rb
> +class CreateShops < ActiveRecord::Migration[7.1]
這個名稱不應該叫做 create shop

2023-12-20 07:52 UTC, sammong approved these changes

2023-12-20 07:57 UTC, Qkauia commented on config/routes.rb
>      root 'products#index'
收到

2023-12-20 09:03 UTC, ennis-hong approved these changes

2023-12-21 03:02 UTC, Adoraxuu approved these changes

2023-12-21 03:15 UTC, Adoraxuu approved these changes

2023-12-21 04:13 UTC, cacachang approved these changes

2023-12-21 04:14 UTC, cacachang commented
add_index_to_shop 這個 migration 可以取得更「直白」一點，我先讓他過

2023-12-21 04:14 UTC, merged