Feat/issue 22
astrocamp/15th-RestTime pull request #42
Opened 2023-12-21 08:57 UTC by Dorenchen

完成修改 會員 密碼

2023-12-21 14:01 UTC, sammong approved these changes
Well done.

2023-12-21 14:28 UTC, Adoraxuu commented on app/views/shared/_navbar.html.erb
這裡我和你會有衝突，我和你新增的地方都要留下來～

2023-12-21 14:28 UTC, Adoraxuu approved these changes

2023-12-21 14:47 UTC, ennis-hong requested changes

2023-12-21 14:47 UTC, ennis-hong commented on app/views/devise/registrations/edit.html.erb
訊息內容及標題名稱要用i18n唷

2023-12-21 19:18 UTC, Qkauia approved these changes

2023-12-22 03:18 UTC, ennis-hong approved these changes
我先過後面記得補i18n

2023-12-22 03:28 UTC, cacachang requested changes
想問這個功能有測過嗎？我測起來修改密碼無效哦

> 功能沒事，是我眼殘

2023-12-22 10:52 UTC, merged