新增店家i18n,地圖
astrocamp/15th-RestTime pull request #55
Opened 2023-12-23 14:20 UTC by Qkauia

- google map(抓地址顯示)
![截圖 2023-12-23 晚上10 03 37](https://github.com/astrocamp/15th-RestTime/assets/114802512/fcb65be3-6d25-4ef7-b503-2c830ba2b515)
- 登入與沒登入判斷
- 登入
![截圖 2023-12-23 晚上10 04 38](https://github.com/astrocamp/15th-RestTime/assets/114802512/0e93893f-52e9-408b-ab6a-c2acb0fd8a5d)
- 未登入
![截圖 2023-12-23 晚上10 17 23](https://github.com/astrocamp/15th-RestTime/assets/114802512/5ba6d6e1-c829-472e-9987-55c5fdd741e9)
- 重新建立店家會轉到422

2023-12-23 16:08 UTC, Adoraxuu approved these changes

2023-12-24 04:55 UTC, Dorenchen approved these changes

2023-12-24 05:49 UTC, ennis-hong commented on app/views/shops/show.html.erb
![image](https://github.com/astrocamp/15th-RestTime/assets/8993798/4c0512bd-43aa-42a8-86f7-8faa3ca28990)
有打錯字

2023-12-24 05:59 UTC, ennis-hong requested changes
營業時間連結請補回

2023-12-24 05:59 UTC, ennis-hong commented on app/views/shops/_form_select_shop_status.html.erb
- i18n
![image](https://github.com/astrocamp/15th-RestTime/assets/8993798/d258b533-7b03-4057-a19a-8e6c9c074d50)

2023-12-24 07:57 UTC, Adoraxuu approved these changes

2023-12-24 07:59 UTC, Adoraxuu commented on app/controllers/shops_controller.rb
因為有新增User.role
我先過，不過之後判斷可能會要調整一下～

2023-12-24 08:00 UTC, Adoraxuu approved these changes

2023-12-24 08:54 UTC, ennis-hong approved these changes

2023-12-24 08:54 UTC, merged

2023-12-25 03:17 UTC, cacachang commented on app/controllers/shops_controller.rb
> +  def check_shop_presence
想問為什麼要提前判斷？看起來提前判斷好像也沒幹嘛

2023-12-25 03:17 UTC, cacachang commented on app/controllers/shops_controller.rb
> +    if current_user == @shop
current_user == shop 這句是什麼意思呢？

是指 shop 的 owner 是 current_user 嗎？
這應該也不需要放在 callback 中
也可以用 pundit 做掉

2023-12-25 03:17 UTC, cacachang commented on app/models/shop.rb
> +  enum status: { closed: 'closed', open: 'open', busy: 'busy', shut_down: 'ShutDown' }
可以用 integer 去存