加入i18n效果
astrocamp/15th-RestTime pull request #82
Opened 2023-12-29 07:27 UTC by Dorenchen

![螢幕擷取畫面 2023-12-29 152630](https://github.com/astrocamp/15th-RestTime/assets/149484247/ec6d6d9d-9919-46a2-a00c-cbdf51609826)
![螢幕擷取畫面 2023-12-29 152635](https://github.com/astrocamp/15th-RestTime/assets/149484247/22f996ba-944c-44c6-bbb2-e2cda49e46e6)

2023-12-31 07:30 UTC, Qkauia approved these changes

2023-12-31 17:01 UTC, ennis-hong approved these changes

2024-01-02 02:45 UTC, cacachang requested changes

2024-01-02 02:45 UTC, cacachang commented on app/controllers/users/omniauth_callbacks_controller.rb
> +  skip_before_action :verify_authenticity_token, only: [:google_oauth2]
這有跑過 rubocop 嗎

2024-01-02 02:45 UTC, cacachang commented on app/models/user.rb
> +  def self.from_omniauth(access_token)
為什麼要多放一個？下面有這個方法了

2024-01-02 04:25 UTC, Dorenchen commented on app/controllers/users/omniauth_callbacks_controller.rb
> +  skip_before_action :verify_authenticity_token, only: [:google_oauth2]
最新的處理了

2024-01-02 04:32 UTC, Dorenchen commented on app/models/user.rb
> +  def self.from_omniauth(access_token)
已處理

2024-01-02 09:49 UTC, cacachang approved these changes

2024-01-02 09:50 UTC, merged